// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Bank is the predicate function for bank builders.
type Bank func(*sql.Selector)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// Confirmation is the predicate function for confirmation builders.
type Confirmation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
