// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/patza/app/ent/bank"
	"github.com/patza/app/ent/bill"
	"github.com/patza/app/ent/confirmation"
	"github.com/patza/app/ent/predicate"
	"github.com/patza/app/ent/user"
)

// BillUpdate is the builder for updating Bill entities.
type BillUpdate struct {
	config
	hooks      []Hook
	mutation   *BillMutation
	predicates []predicate.Bill
}

// Where adds a new predicate for the builder.
func (bu *BillUpdate) Where(ps ...predicate.Bill) *BillUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetPayNumber sets the Pay_number field.
func (bu *BillUpdate) SetPayNumber(i int) *BillUpdate {
	bu.mutation.ResetPayNumber()
	bu.mutation.SetPayNumber(i)
	return bu
}

// AddPayNumber adds i to Pay_number.
func (bu *BillUpdate) AddPayNumber(i int) *BillUpdate {
	bu.mutation.AddPayNumber(i)
	return bu
}

// SetPayTotal sets the Pay_total field.
func (bu *BillUpdate) SetPayTotal(i int) *BillUpdate {
	bu.mutation.ResetPayTotal()
	bu.mutation.SetPayTotal(i)
	return bu
}

// AddPayTotal adds i to Pay_total.
func (bu *BillUpdate) AddPayTotal(i int) *BillUpdate {
	bu.mutation.AddPayTotal(i)
	return bu
}

// SetPayTime sets the Pay_time field.
func (bu *BillUpdate) SetPayTime(t time.Time) *BillUpdate {
	bu.mutation.SetPayTime(t)
	return bu
}

// SetBankID sets the bank edge to Bank by id.
func (bu *BillUpdate) SetBankID(id int) *BillUpdate {
	bu.mutation.SetBankID(id)
	return bu
}

// SetNillableBankID sets the bank edge to Bank by id if the given value is not nil.
func (bu *BillUpdate) SetNillableBankID(id *int) *BillUpdate {
	if id != nil {
		bu = bu.SetBankID(*id)
	}
	return bu
}

// SetBank sets the bank edge to Bank.
func (bu *BillUpdate) SetBank(b *Bank) *BillUpdate {
	return bu.SetBankID(b.ID)
}

// SetConfirmationID sets the confirmation edge to Confirmation by id.
func (bu *BillUpdate) SetConfirmationID(id int) *BillUpdate {
	bu.mutation.SetConfirmationID(id)
	return bu
}

// SetNillableConfirmationID sets the confirmation edge to Confirmation by id if the given value is not nil.
func (bu *BillUpdate) SetNillableConfirmationID(id *int) *BillUpdate {
	if id != nil {
		bu = bu.SetConfirmationID(*id)
	}
	return bu
}

// SetConfirmation sets the confirmation edge to Confirmation.
func (bu *BillUpdate) SetConfirmation(c *Confirmation) *BillUpdate {
	return bu.SetConfirmationID(c.ID)
}

// SetOwnerID sets the owner edge to User by id.
func (bu *BillUpdate) SetOwnerID(id int) *BillUpdate {
	bu.mutation.SetOwnerID(id)
	return bu
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (bu *BillUpdate) SetNillableOwnerID(id *int) *BillUpdate {
	if id != nil {
		bu = bu.SetOwnerID(*id)
	}
	return bu
}

// SetOwner sets the owner edge to User.
func (bu *BillUpdate) SetOwner(u *User) *BillUpdate {
	return bu.SetOwnerID(u.ID)
}

// Mutation returns the BillMutation object of the builder.
func (bu *BillUpdate) Mutation() *BillMutation {
	return bu.mutation
}

// ClearBank clears the bank edge to Bank.
func (bu *BillUpdate) ClearBank() *BillUpdate {
	bu.mutation.ClearBank()
	return bu
}

// ClearConfirmation clears the confirmation edge to Confirmation.
func (bu *BillUpdate) ClearConfirmation() *BillUpdate {
	bu.mutation.ClearConfirmation()
	return bu
}

// ClearOwner clears the owner edge to User.
func (bu *BillUpdate) ClearOwner() *BillUpdate {
	bu.mutation.ClearOwner()
	return bu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BillUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := bu.mutation.PayNumber(); ok {
		if err := bill.PayNumberValidator(v); err != nil {
			return 0, &ValidationError{Name: "Pay_number", err: fmt.Errorf("ent: validator failed for field \"Pay_number\": %w", err)}
		}
	}
	if v, ok := bu.mutation.PayTotal(); ok {
		if err := bill.PayTotalValidator(v); err != nil {
			return 0, &ValidationError{Name: "Pay_total", err: fmt.Errorf("ent: validator failed for field \"Pay_total\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BillUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BillUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BillUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BillUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bill.Table,
			Columns: bill.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bill.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.PayNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayNumber,
		})
	}
	if value, ok := bu.mutation.AddedPayNumber(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayNumber,
		})
	}
	if value, ok := bu.mutation.PayTotal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayTotal,
		})
	}
	if value, ok := bu.mutation.AddedPayTotal(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayTotal,
		})
	}
	if value, ok := bu.mutation.PayTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bill.FieldPayTime,
		})
	}
	if bu.mutation.BankCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.BankTable,
			Columns: []string{bill.BankColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bank.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.BankIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.BankTable,
			Columns: []string{bill.BankColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bank.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.ConfirmationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ConfirmationTable,
			Columns: []string{bill.ConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ConfirmationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ConfirmationTable,
			Columns: []string{bill.ConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.OwnerTable,
			Columns: []string{bill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.OwnerTable,
			Columns: []string{bill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bill.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BillUpdateOne is the builder for updating a single Bill entity.
type BillUpdateOne struct {
	config
	hooks    []Hook
	mutation *BillMutation
}

// SetPayNumber sets the Pay_number field.
func (buo *BillUpdateOne) SetPayNumber(i int) *BillUpdateOne {
	buo.mutation.ResetPayNumber()
	buo.mutation.SetPayNumber(i)
	return buo
}

// AddPayNumber adds i to Pay_number.
func (buo *BillUpdateOne) AddPayNumber(i int) *BillUpdateOne {
	buo.mutation.AddPayNumber(i)
	return buo
}

// SetPayTotal sets the Pay_total field.
func (buo *BillUpdateOne) SetPayTotal(i int) *BillUpdateOne {
	buo.mutation.ResetPayTotal()
	buo.mutation.SetPayTotal(i)
	return buo
}

// AddPayTotal adds i to Pay_total.
func (buo *BillUpdateOne) AddPayTotal(i int) *BillUpdateOne {
	buo.mutation.AddPayTotal(i)
	return buo
}

// SetPayTime sets the Pay_time field.
func (buo *BillUpdateOne) SetPayTime(t time.Time) *BillUpdateOne {
	buo.mutation.SetPayTime(t)
	return buo
}

// SetBankID sets the bank edge to Bank by id.
func (buo *BillUpdateOne) SetBankID(id int) *BillUpdateOne {
	buo.mutation.SetBankID(id)
	return buo
}

// SetNillableBankID sets the bank edge to Bank by id if the given value is not nil.
func (buo *BillUpdateOne) SetNillableBankID(id *int) *BillUpdateOne {
	if id != nil {
		buo = buo.SetBankID(*id)
	}
	return buo
}

// SetBank sets the bank edge to Bank.
func (buo *BillUpdateOne) SetBank(b *Bank) *BillUpdateOne {
	return buo.SetBankID(b.ID)
}

// SetConfirmationID sets the confirmation edge to Confirmation by id.
func (buo *BillUpdateOne) SetConfirmationID(id int) *BillUpdateOne {
	buo.mutation.SetConfirmationID(id)
	return buo
}

// SetNillableConfirmationID sets the confirmation edge to Confirmation by id if the given value is not nil.
func (buo *BillUpdateOne) SetNillableConfirmationID(id *int) *BillUpdateOne {
	if id != nil {
		buo = buo.SetConfirmationID(*id)
	}
	return buo
}

// SetConfirmation sets the confirmation edge to Confirmation.
func (buo *BillUpdateOne) SetConfirmation(c *Confirmation) *BillUpdateOne {
	return buo.SetConfirmationID(c.ID)
}

// SetOwnerID sets the owner edge to User by id.
func (buo *BillUpdateOne) SetOwnerID(id int) *BillUpdateOne {
	buo.mutation.SetOwnerID(id)
	return buo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (buo *BillUpdateOne) SetNillableOwnerID(id *int) *BillUpdateOne {
	if id != nil {
		buo = buo.SetOwnerID(*id)
	}
	return buo
}

// SetOwner sets the owner edge to User.
func (buo *BillUpdateOne) SetOwner(u *User) *BillUpdateOne {
	return buo.SetOwnerID(u.ID)
}

// Mutation returns the BillMutation object of the builder.
func (buo *BillUpdateOne) Mutation() *BillMutation {
	return buo.mutation
}

// ClearBank clears the bank edge to Bank.
func (buo *BillUpdateOne) ClearBank() *BillUpdateOne {
	buo.mutation.ClearBank()
	return buo
}

// ClearConfirmation clears the confirmation edge to Confirmation.
func (buo *BillUpdateOne) ClearConfirmation() *BillUpdateOne {
	buo.mutation.ClearConfirmation()
	return buo
}

// ClearOwner clears the owner edge to User.
func (buo *BillUpdateOne) ClearOwner() *BillUpdateOne {
	buo.mutation.ClearOwner()
	return buo
}

// Save executes the query and returns the updated entity.
func (buo *BillUpdateOne) Save(ctx context.Context) (*Bill, error) {
	if v, ok := buo.mutation.PayNumber(); ok {
		if err := bill.PayNumberValidator(v); err != nil {
			return nil, &ValidationError{Name: "Pay_number", err: fmt.Errorf("ent: validator failed for field \"Pay_number\": %w", err)}
		}
	}
	if v, ok := buo.mutation.PayTotal(); ok {
		if err := bill.PayTotalValidator(v); err != nil {
			return nil, &ValidationError{Name: "Pay_total", err: fmt.Errorf("ent: validator failed for field \"Pay_total\": %w", err)}
		}
	}

	var (
		err  error
		node *Bill
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BillUpdateOne) SaveX(ctx context.Context) *Bill {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BillUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BillUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BillUpdateOne) sqlSave(ctx context.Context) (b *Bill, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bill.Table,
			Columns: bill.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bill.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Bill.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.PayNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayNumber,
		})
	}
	if value, ok := buo.mutation.AddedPayNumber(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayNumber,
		})
	}
	if value, ok := buo.mutation.PayTotal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayTotal,
		})
	}
	if value, ok := buo.mutation.AddedPayTotal(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldPayTotal,
		})
	}
	if value, ok := buo.mutation.PayTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bill.FieldPayTime,
		})
	}
	if buo.mutation.BankCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.BankTable,
			Columns: []string{bill.BankColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bank.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.BankIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.BankTable,
			Columns: []string{bill.BankColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bank.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.ConfirmationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ConfirmationTable,
			Columns: []string{bill.ConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ConfirmationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ConfirmationTable,
			Columns: []string{bill.ConfirmationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: confirmation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.OwnerTable,
			Columns: []string{bill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.OwnerTable,
			Columns: []string{bill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Bill{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bill.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
