// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/patza/app/ent/bill"
	"github.com/patza/app/ent/schema"
	"github.com/patza/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	billFields := schema.Bill{}.Fields()
	_ = billFields
	// billDescPayNumber is the schema descriptor for Pay_number field.
	billDescPayNumber := billFields[0].Descriptor()
	// bill.PayNumberValidator is a validator for the "Pay_number" field. It is called by the builders before save.
	bill.PayNumberValidator = billDescPayNumber.Validators[0].(func(int) error)
	// billDescPayTotal is the schema descriptor for Pay_total field.
	billDescPayTotal := billFields[1].Descriptor()
	// bill.PayTotalValidator is a validator for the "Pay_total" field. It is called by the builders before save.
	bill.PayTotalValidator = billDescPayTotal.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
}
