// Code generated by entc, DO NOT EDIT.

package bank

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/patza/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Bank applies equality check predicate on the "Bank" field. It's identical to BankEQ.
func Bank(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBank), v))
	})
}

// BankEQ applies the EQ predicate on the "Bank" field.
func BankEQ(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBank), v))
	})
}

// BankNEQ applies the NEQ predicate on the "Bank" field.
func BankNEQ(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBank), v))
	})
}

// BankIn applies the In predicate on the "Bank" field.
func BankIn(vs ...string) predicate.Bank {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bank(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBank), v...))
	})
}

// BankNotIn applies the NotIn predicate on the "Bank" field.
func BankNotIn(vs ...string) predicate.Bank {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bank(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBank), v...))
	})
}

// BankGT applies the GT predicate on the "Bank" field.
func BankGT(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBank), v))
	})
}

// BankGTE applies the GTE predicate on the "Bank" field.
func BankGTE(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBank), v))
	})
}

// BankLT applies the LT predicate on the "Bank" field.
func BankLT(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBank), v))
	})
}

// BankLTE applies the LTE predicate on the "Bank" field.
func BankLTE(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBank), v))
	})
}

// BankContains applies the Contains predicate on the "Bank" field.
func BankContains(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBank), v))
	})
}

// BankHasPrefix applies the HasPrefix predicate on the "Bank" field.
func BankHasPrefix(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBank), v))
	})
}

// BankHasSuffix applies the HasSuffix predicate on the "Bank" field.
func BankHasSuffix(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBank), v))
	})
}

// BankEqualFold applies the EqualFold predicate on the "Bank" field.
func BankEqualFold(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBank), v))
	})
}

// BankContainsFold applies the ContainsFold predicate on the "Bank" field.
func BankContainsFold(v string) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBank), v))
	})
}

// HasBill applies the HasEdge predicate on the "bill" edge.
func HasBill() predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BillTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillTable, BillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillWith applies the HasEdge predicate on the "bill" edge with a given conditions (other predicates).
func HasBillWith(preds ...predicate.Bill) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(BillInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillTable, BillColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Bank) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Bank) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bank) predicate.Bank {
	return predicate.Bank(func(s *sql.Selector) {
		p(s.Not())
	})
}
