// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BanksColumns holds the columns for the "banks" table.
	BanksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bank", Type: field.TypeString, Unique: true},
	}
	// BanksTable holds the schema information for the "banks" table.
	BanksTable = &schema.Table{
		Name:        "banks",
		Columns:     BanksColumns,
		PrimaryKey:  []*schema.Column{BanksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pay_number", Type: field.TypeInt, Unique: true},
		{Name: "pay_total", Type: field.TypeInt},
		{Name: "pay_time", Type: field.TypeTime},
		{Name: "bank_id", Type: field.TypeInt, Nullable: true},
		{Name: "confirmation_id", Type: field.TypeInt, Nullable: true},
		{Name: "owner_id", Type: field.TypeInt, Nullable: true},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "bills_banks_bill",
				Columns: []*schema.Column{BillsColumns[4]},

				RefColumns: []*schema.Column{BanksColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "bills_confirmations_bill",
				Columns: []*schema.Column{BillsColumns[5]},

				RefColumns: []*schema.Column{ConfirmationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "bills_users_bill",
				Columns: []*schema.Column{BillsColumns[6]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ConfirmationsColumns holds the columns for the "confirmations" table.
	ConfirmationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "adddate", Type: field.TypeTime},
		{Name: "bookingstart", Type: field.TypeTime},
		{Name: "bookingend", Type: field.TypeTime},
		{Name: "hourstime", Type: field.TypeInt},
		{Name: "owner_id", Type: field.TypeInt, Nullable: true},
	}
	// ConfirmationsTable holds the schema information for the "confirmations" table.
	ConfirmationsTable = &schema.Table{
		Name:       "confirmations",
		Columns:    ConfirmationsColumns,
		PrimaryKey: []*schema.Column{ConfirmationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "confirmations_users_confirmation",
				Columns: []*schema.Column{ConfirmationsColumns[5]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "birth", Type: field.TypeTime},
		{Name: "tel", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BanksTable,
		BillsTable,
		ConfirmationsTable,
		UsersTable,
	}
)

func init() {
	BillsTable.ForeignKeys[0].RefTable = BanksTable
	BillsTable.ForeignKeys[1].RefTable = ConfirmationsTable
	BillsTable.ForeignKeys[2].RefTable = UsersTable
	ConfirmationsTable.ForeignKeys[0].RefTable = UsersTable
}
