// Code generated by entc, DO NOT EDIT.

package confirmation

const (
	// Label holds the string label denoting the confirmation type in the database.
	Label = "confirmation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdddate holds the string denoting the adddate field in the database.
	FieldAdddate = "adddate"
	// FieldBookingstart holds the string denoting the bookingstart field in the database.
	FieldBookingstart = "bookingstart"
	// FieldBookingend holds the string denoting the bookingend field in the database.
	FieldBookingend = "bookingend"
	// FieldHourstime holds the string denoting the hourstime field in the database.
	FieldHourstime = "hourstime"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeBill holds the string denoting the bill edge name in mutations.
	EdgeBill = "bill"

	// Table holds the table name of the confirmation in the database.
	Table = "confirmations"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "confirmations"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// BillTable is the table the holds the bill relation/edge.
	BillTable = "bills"
	// BillInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BillInverseTable = "bills"
	// BillColumn is the table column denoting the bill relation/edge.
	BillColumn = "confirmation_id"
)

// Columns holds all SQL columns for confirmation fields.
var Columns = []string{
	FieldID,
	FieldAdddate,
	FieldBookingstart,
	FieldBookingend,
	FieldHourstime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Confirmation type.
var ForeignKeys = []string{
	"owner_id",
}
