/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBankEdges
 */
export interface EntBankEdges {
    /**
     * Bill holds the value of the bill edge.
     * @type {Array<EntBill>}
     * @memberof EntBankEdges
     */
    bill?: Array<EntBill>;
}

export function EntBankEdgesFromJSON(json: any): EntBankEdges {
    return EntBankEdgesFromJSONTyped(json, false);
}

export function EntBankEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBankEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bill': !exists(json, 'bill') ? undefined : ((json['bill'] as Array<any>).map(EntBillFromJSON)),
    };
}

export function EntBankEdgesToJSON(value?: EntBankEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bill': value.bill === undefined ? undefined : ((value.bill as Array<any>).map(EntBillToJSON)),
    };
}


