/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBank,
    EntBankFromJSON,
    EntBankFromJSONTyped,
    EntBankToJSON,
    EntConfirmation,
    EntConfirmationFromJSON,
    EntConfirmationFromJSONTyped,
    EntConfirmationToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBillEdges
 */
export interface EntBillEdges {
    /**
     * 
     * @type {EntBank}
     * @memberof EntBillEdges
     */
    bank?: EntBank;
    /**
     * 
     * @type {EntConfirmation}
     * @memberof EntBillEdges
     */
    confirmation?: EntConfirmation;
    /**
     * 
     * @type {EntUser}
     * @memberof EntBillEdges
     */
    owner?: EntUser;
}

export function EntBillEdgesFromJSON(json: any): EntBillEdges {
    return EntBillEdgesFromJSONTyped(json, false);
}

export function EntBillEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBillEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bank': !exists(json, 'bank') ? undefined : EntBankFromJSON(json['bank']),
        'confirmation': !exists(json, 'confirmation') ? undefined : EntConfirmationFromJSON(json['confirmation']),
        'owner': !exists(json, 'owner') ? undefined : EntUserFromJSON(json['owner']),
    };
}

export function EntBillEdgesToJSON(value?: EntBillEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bank': EntBankToJSON(value.bank),
        'confirmation': EntConfirmationToJSON(value.confirmation),
        'owner': EntUserToJSON(value.owner),
    };
}


