/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBankEdges,
    EntBankEdgesFromJSON,
    EntBankEdgesFromJSONTyped,
    EntBankEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBank
 */
export interface EntBank {
    /**
     * Bank holds the value of the "Bank" field.
     * @type {string}
     * @memberof EntBank
     */
    bank?: string;
    /**
     * 
     * @type {EntBankEdges}
     * @memberof EntBank
     */
    edges?: EntBankEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBank
     */
    id?: number;
}

export function EntBankFromJSON(json: any): EntBank {
    return EntBankFromJSONTyped(json, false);
}

export function EntBankFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBank {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bank': !exists(json, 'Bank') ? undefined : json['Bank'],
        'edges': !exists(json, 'edges') ? undefined : EntBankEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBankToJSON(value?: EntBank | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Bank': value.bank,
        'edges': EntBankEdgesToJSON(value.edges),
        'id': value.id,
    };
}


