/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntConfirmationEdges
 */
export interface EntConfirmationEdges {
    /**
     * Bill holds the value of the bill edge.
     * @type {Array<EntBill>}
     * @memberof EntConfirmationEdges
     */
    bill?: Array<EntBill>;
    /**
     * 
     * @type {EntUser}
     * @memberof EntConfirmationEdges
     */
    owner?: EntUser;
}

export function EntConfirmationEdgesFromJSON(json: any): EntConfirmationEdges {
    return EntConfirmationEdgesFromJSONTyped(json, false);
}

export function EntConfirmationEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntConfirmationEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bill': !exists(json, 'bill') ? undefined : ((json['bill'] as Array<any>).map(EntBillFromJSON)),
        'owner': !exists(json, 'owner') ? undefined : EntUserFromJSON(json['owner']),
    };
}

export function EntConfirmationEdgesToJSON(value?: EntConfirmationEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bill': value.bill === undefined ? undefined : ((value.bill as Array<any>).map(EntBillToJSON)),
        'owner': EntUserToJSON(value.owner),
    };
}


