// Code generated by entc, DO NOT EDIT.

package bill

const (
	// Label holds the string label denoting the bill type in the database.
	Label = "bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPayNumber holds the string denoting the pay_number field in the database.
	FieldPayNumber = "pay_number"
	// FieldPayTotal holds the string denoting the pay_total field in the database.
	FieldPayTotal = "pay_total"
	// FieldPayTime holds the string denoting the pay_time field in the database.
	FieldPayTime = "pay_time"

	// EdgeBank holds the string denoting the bank edge name in mutations.
	EdgeBank = "bank"
	// EdgeConfirmation holds the string denoting the confirmation edge name in mutations.
	EdgeConfirmation = "confirmation"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the bill in the database.
	Table = "bills"
	// BankTable is the table the holds the bank relation/edge.
	BankTable = "bills"
	// BankInverseTable is the table name for the Bank entity.
	// It exists in this package in order to avoid circular dependency with the "bank" package.
	BankInverseTable = "banks"
	// BankColumn is the table column denoting the bank relation/edge.
	BankColumn = "bank_id"
	// ConfirmationTable is the table the holds the confirmation relation/edge.
	ConfirmationTable = "bills"
	// ConfirmationInverseTable is the table name for the Confirmation entity.
	// It exists in this package in order to avoid circular dependency with the "confirmation" package.
	ConfirmationInverseTable = "confirmations"
	// ConfirmationColumn is the table column denoting the confirmation relation/edge.
	ConfirmationColumn = "confirmation_id"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "bills"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
)

// Columns holds all SQL columns for bill fields.
var Columns = []string{
	FieldID,
	FieldPayNumber,
	FieldPayTotal,
	FieldPayTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Bill type.
var ForeignKeys = []string{
	"bank_id",
	"confirmation_id",
	"owner_id",
}

var (
	// PayNumberValidator is a validator for the "Pay_number" field. It is called by the builders before save.
	PayNumberValidator func(int) error
	// PayTotalValidator is a validator for the "Pay_total" field. It is called by the builders before save.
	PayTotalValidator func(int) error
)
